name: "Build web artifact"

on:
  pull_request:
    branches:
      - main
  # remove on push when moving to apps; this is just for faster GHA testing
  # push:
  #   branches:
  #     - main

jobs:
  empty:
    runs-on: ubuntu-latest
    steps:
      - name: empty
        run: echo "building"