name: "Create Percy screenshots"

on:
  workflow_run:
    workflows:
      - "Upload artifacts for Percy screenshots"
    types:
      - completed

jobs:
  upload:
    name: Build project with proposed changes & take Percy snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Verify that triggering workflow run passed
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Previous workflow run was not successful."
            exit 1
          else
            echo "Previous workflow run was successful."
          fi
      - name: Checkout SCM
        uses: actions/checkout@v4

      - name: Download artifact from workflow run
        uses: actions/download-artifact@v4
        with:
          name: "web-artifact-${{ github.event.workflow_run.id }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Install Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.10.14

      - name: Install NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn && pip3 install -r requirements.txt

      - name: Replace SCM files with artifact files
        run: |
          set -e
          rm -rf templates/ scss/ 
          tar xzf build.tar.gz 
          rm build.tar.gz

      - name: Build
        run: yarn build

      - name: Start testing server
        env:
          SECRET_KEY: local_development_fake_key
        run: ./entrypoint 0.0.0.0:8101 &

      - name: Wait for server availability
        run: |
          while true; do
            if curl -sSf "http://0.0.0.0:8101" > /dev/null; then
              break
            else
              echo "Waiting for server to start..."
              sleep 2
            fi
          done

      - name: Take screenshots
        run: yarn percy

  # Add a check to the PR based on the percy status
  # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
  apply_pr_check:
    needs: upload
    if: github.event.workflow_run.pull_requests[0] != null
    runs-on: ubuntu-latest
    steps:
      - name: Apply PR check
        run: |
          response = $(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{
              "name": "Screenshots succeeded",
              "head_sha": "${{ github.event.workflow_run.pull_requests[0].head.sha }}",
              "status": "completed",
              "conclusion": "success",
              "output": {
                "title": "Percy screenshots diff",
                "summary": "A summary of the test check run"
              }
            }' \
            "https://api.github.com/repos/${{ github.repository.full_name }}/check-runs")
            response_code=$(echo "$response" | tail -n1)
            if [ "$response_code" != "201" ]; then
              echo "Failed to create check run. Response code: $response_code"
              exit 1
            fi