name: "Copy "

on:
  pull_request:
    branches:
      - main
  # remove on push when moving to apps; this is just for faster GHA testing
  push:
    branches:
      - main

jobs:
  empty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            templates/
            scss/

      - name: Compress artifact
        run: tar -czf build.tar.gz templates/ scss/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "web-artifact-${{ github.run_id }}"
          path: build.tar.gz