name: "Upload screenshots"

on:
  workflow_run:
    workflows:
      - "Build web artifact"
    types:
      - completed

jobs:
  validate_workflow_trigger:
    if: "! github.event.pull_request.head.repo.fork "
    runs-on: ubuntu-latest
    steps: 
      - name: Verify that triggering workflow run passed
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Previous workflow run was not successful."
            exit 1
          else
            echo "Previous workflow run was successful."
          fi
  test:
    # only run on base repo
    needs: validate_workflow_trigger
    runs-on: ubuntu-latest
    steps:
      - name: Verify correct secrets access
        run: |
          if [[ -z "${{ secrets.TEST_SECRET }}" ]]; then
            echo "No access to secrets in the base repo."
            exit 1
          else
            echo "We have proper access to secrets in the base repo."
          fi

  upload:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from workflow run
        uses: actions/download-artifact@v4
        with:
          name: "web-artifact-${{ github.event.workflow_run.workflow_id }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.repository }}
      - name: Replace SCM files with artifact files
        run: |
          set -e
          rm -rf templates/ scss/ 
          tar xzf build.tar.gz 
          rm build.tar.gz
          tree